### ISSUE TITLE
Add better error messages

### ISSUE THREAD

**Issue by vongaisberg** [KillingSpark/sparkpass#2]
`sparkpass --help` tells the user to look at `man pass` for a list of available commands. The first command that is listed there and would be used to initialize a `pass` repo, is `pass init`, which doesn't seem to be required for `sparkpass`.
If a user is used to the syntax of `pass` and tries to initialize a repo by entering `sparkpass init`, they would not receive a meaningful error message telling them that this is unnecessary.

This should be fixed.

**Comment by KillingSpark** [comment]
This is correct, I should have specified that the list of commands only applies to the usage where original pass already has a repo to work with.

Would you rather like a init command that just creates the specified directory if necessary or an error message explaining that there is no need to use "init"? I think it would be better to have the init command to just do nothing / create the directory so it can act more as a drop-in solution.

In the future I would like to have my own documentation, which would clarify that "init" is not necessary anyways so there would be no need for users to read the manpage of original pass.

**Comment by vongaisberg** [comment]
I actually like your idea. `init` should create the directory but tell the user that it was not necessary to do that. Something like: 
A repository was created at ~/.sparkpass
Running sparkpass init is not required, this would have automatically happened when you add your first password.

**Comment by vongaisberg** [comment]
Another thing I noticed: There is currently no error message for wrong password.

**Comment by KillingSpark** [comment]
> Another thing I noticed: There is currently no error message for wrong password.

This is somewhat tricky to check for actually. I had some ideas none of which I particularly like.

1. Add an entry that always decrypts the same and can be used to check the password. This is probably a bad idea from a cryptographical standpoint. It also forces exactly one master-key per repo. Right now it's actually fine to use as many master-keys as you like as long as you remember which entry needs which key.

2. Prefix each file with a known string like "Entry". This could easily be stripped before printing the content. But it feels very wonky.

3. Check whether the output of the decryption is at least valid utf-8 encoded data. This would probably catch many cases but is not guaranteed to work.

I will think about this, because I very much agree that this is important for the user experience, if you have any suggestions please share them :)

**Comment by vongaisberg** [comment]
Number 3 is not compatible with my conscience, it is just bad.

I have used both 1 and 2 in shitty projects of mine (one was on a TI-84+).

I don't know enough about encryption, but I don't know if 1 is actually that bad for security. If you want the user to know if a password is correct, attackers will as well, there is now way around this.

I like version 2 the most, since it requires no additional files in the directory. You should. Probably use something a little longer than "Entry", it feels too short.

**Comment by KillingSpark** [comment]
> I actually like your idea. `init` should create the directory but tell the user that it was not necessary to do that. Something like:
> A repository was created at ~/.sparkpass
> Running sparkpass init is not required, this would have automatically happened when you add your first password.

This has been added. I will open a new issue for the master-key checking.

**Comment by KillingSpark** [comment]
See #4
